PROJECT=main
TEX=pdflatex
BUILDTEX=$(TEX) $(PROJECT).tex

all:
	$(BUILDTEX)
	$(BUILDTEX)
	$(BUILDTEX)

clean-all:
	rm -f *.dvi *.log *.pdf *~
clean:
	rm -f *.log *.bak *.pdf *.aux *.bbl *.blg *.toc *~

